always_show_default = true
command = 'xdg-open'
engines_as_actions = false
history = true
history_when_empty = false
text_prefix = 'Search: '

[Config]
hide_from_providerlist = false
icon = 'applications-internet'
min_score = 20
name_pretty = ''

[[entries]]
default = true
icon = ''
name = 'Google'
prefix = ''
url = 'https://www.google.com/search?q=%TERM%'

[[entries]]
default = false
icon = ''
name = 'DuckDuckGo'
prefix = ''
url = 'https://duckduckgo.com/?q=%TERM%'

[[entries]]
default = false
icon = ''
name = 'GitHub'
prefix = ''
url = 'https://github.com/search?q=%TERM%'

[[entries]]
default = false
icon = ''
name = 'YouTube'
prefix = ''
url = 'https://www.youtube.com/results?search_query=%TERM%'

[[entries]]
default = false
icon = ''
name = 'Wikipedia'
prefix = ''
url = 'https://en.wikipedia.org/w/index.php?search=%TERM%'

[[entries]]
default = false
icon = ''
name = 'Stack Overflow'
prefix = ''
url = 'https://stackoverflow.com/search?q=%TERM%'

[[entries]]
default = false
icon = ''
name = 'Arch Wiki'
prefix = ''
url = 'https://wiki.archlinux.org/index.php?search=%TERM%'

[[entries]]
default = false
icon = ''
name = 'AUR'
prefix = ''
url = 'https://aur.archlinux.org/packages?K=%TERM%'
